services:
  - type: web
    name: educampus-app-api-colmas
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && alembic upgrade head"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECTOR_NOMBRE
        sync: false
      - key: PYTHON_VERSION
        value: 3.12.7
