"""agregar password encriptado reversible

Revision ID: 17fc57a3e4ec
Revises: 52bb02323359
Create Date: 2026-09-24 16:27:49.760445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17fc57a3e4ec'
down_revision: Union[str, Sequence[str], None] = '52bb02323359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acudientes', sa.Column('password_encrypted', sa.Text(), nullable=True))
    op.add_column('administradores', sa.Column('password_encrypted', sa.Text(), nullable=True))
    op.add_column('estudiantes', sa.Column('password_encrypted', sa.Text(), nullable=True))
    op.add_column('profesores', sa.Column('password_encrypted', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesores', 'password_encrypted')
    op.drop_column('estudiantes', 'password_encrypted')
    op.drop_column('administradores', 'password_encrypted')
    op.drop_column('acudientes', 'password_encrypted')
    # ### end Alembic commands ###
