"""agregar firma digital a profesores y administradores

Revision ID: 2a47c321d4a6
Revises: 17fc57a3e4ec
Create Date: 2026-09-24 17:07:31.582929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a47c321d4a6'
down_revision: Union[str, Sequence[str], None] = '17fc57a3e4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administradores', sa.Column('firma_base64', sa.Text(), nullable=True))
    op.add_column('profesores', sa.Column('firma_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profesores', 'firma_base64')
    op.drop_column('administradores', 'firma_base64')
    # ### end Alembic commands ###
