"""boletin: periodos, desempeno preescolar, observaciones

Revision ID: 4d26d6e6c395
Revises: 9c29252b36d8
Create Date: 2026-09-21 14:38:59.331998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d26d6e6c395'
down_revision: Union[str, Sequence[str], None] = '9c29252b36d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observaciones_boletin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=10), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'periodo', name='uq_observacion_estudiante_periodo')
    )
    op.create_index(op.f('ix_observaciones_boletin_id'), 'observaciones_boletin', ['id'], unique=False)
    op.add_column('calificaciones', sa.Column('periodo', sa.String(length=10), server_default='I', nullable=False))
    op.create_unique_constraint('uq_calificacion_estudiante_curso_periodo', 'calificaciones', ['student_id', 'course_id', 'periodo'])
    op.add_column('grados', sa.Column('es_preescolar', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.add_column('grados', sa.Column('director_grupo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'grados', 'profesores', ['director_grupo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'grados', type_='foreignkey')
    op.drop_column('grados', 'director_grupo_id')
    op.drop_column('grados', 'es_preescolar')
    op.drop_constraint('uq_calificacion_estudiante_curso_periodo', 'calificaciones', type_='unique')
    op.drop_column('calificaciones', 'periodo')
    op.drop_index(op.f('ix_observaciones_boletin_id'), table_name='observaciones_boletin')
    op.drop_table('observaciones_boletin')
    # ### end Alembic commands ###
