"""agregar profesor_id a notificaciones

Revision ID: 52bb02323359
Revises: f808ee378eef
Create Date: 2026-09-24 12:12:25.117388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52bb02323359'
down_revision: Union[str, Sequence[str], None] = 'f808ee378eef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notificaciones', sa.Column('profesor_id', sa.Integer(), nullable=True))
    op.alter_column('notificaciones', 'acudiente_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'notificaciones', 'profesores', ['profesor_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notificaciones', type_='foreignkey')
    op.alter_column('notificaciones', 'acudiente_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('notificaciones', 'profesor_id')
    # ### end Alembic commands ###
