"""agregar tabla de clases finalizadas

Revision ID: 7654e57b857b
Revises: afa31b3bcac9
Create Date: 2026-09-24 01:17:39.999766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7654e57b857b'
down_revision: Union[str, Sequence[str], None] = 'afa31b3bcac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clases_finalizadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clases_finalizadas_id'), 'clases_finalizadas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clases_finalizadas_id'), table_name='clases_finalizadas')
    op.drop_table('clases_finalizadas')
    # ### end Alembic commands ###
