"""asistencia de docentes y reporte diario

Revision ID: 7960d1559421
Revises: 8fe8d54656b6
Create Date: 2026-09-23 20:46:23.840983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7960d1559421'
down_revision: Union[str, Sequence[str], None] = '8fe8d54656b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencias_docentes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profesor_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('completo', sa.Boolean(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profesor_id'], ['profesores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profesor_id', 'fecha', name='uq_asistencia_docente_fecha')
    )
    op.create_index(op.f('ix_asistencias_docentes_id'), 'asistencias_docentes', ['id'], unique=False)
    op.create_unique_constraint('uq_asistencia_estudiante_curso_fecha', 'asistencias', ['student_id', 'course_id', 'fecha'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_asistencia_estudiante_curso_fecha', 'asistencias', type_='unique')
    op.drop_index(op.f('ix_asistencias_docentes_id'), table_name='asistencias_docentes')
    op.drop_table('asistencias_docentes')
    # ### end Alembic commands ###
