"""separar usuarios por rol y agregar entregas

Revision ID: 9c29252b36d8
Revises: fcb67da00dff
Create Date: 2026-09-21 13:23:09.473832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c29252b36d8'
down_revision: Union[str, Sequence[str], None] = 'fcb67da00dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administradores_correo'), 'administradores', ['correo'], unique=True)
    op.create_index(op.f('ix_administradores_id'), 'administradores', ['id'], unique=False)
    op.create_table('tareas_entregas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarea_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('acudiente_id', sa.Integer(), nullable=True),
    sa.Column('archivo_path', sa.Text(), nullable=False),
    sa.Column('archivo_tipo', sa.String(length=30), nullable=False),
    sa.Column('nombre_original', sa.String(length=255), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['acudiente_id'], ['acudientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['tareas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tarea_id', 'student_id', name='uq_entrega_tarea_estudiante')
    )
    op.create_index(op.f('ix_tareas_entregas_id'), 'tareas_entregas', ['id'], unique=False)
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.add_column('acudientes', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('acudientes', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_acudientes_correo'), table_name='acudientes')
    op.create_index(op.f('ix_acudientes_correo'), 'acudientes', ['correo'], unique=True)
    op.add_column('estudiantes', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('estudiantes', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_estudiantes_correo'), table_name='estudiantes')
    op.create_index(op.f('ix_estudiantes_correo'), 'estudiantes', ['correo'], unique=True)
    op.add_column('profesores', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.add_column('profesores', sa.Column('fecha_creacion', sa.DateTime(), nullable=False))
    op.add_column('tareas', sa.Column('permite_video', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas', 'permite_video')
    op.drop_column('profesores', 'fecha_creacion')
    op.drop_column('profesores', 'password_hash')
    op.drop_index(op.f('ix_estudiantes_correo'), table_name='estudiantes')
    op.create_index(op.f('ix_estudiantes_correo'), 'estudiantes', ['correo'], unique=False)
    op.drop_column('estudiantes', 'fecha_creacion')
    op.drop_column('estudiantes', 'password_hash')
    op.drop_index(op.f('ix_acudientes_correo'), table_name='acudientes')
    op.create_index(op.f('ix_acudientes_correo'), 'acudientes', ['correo'], unique=False)
    op.drop_column('acudientes', 'fecha_creacion')
    op.drop_column('acudientes', 'password_hash')
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('correo', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('rol', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.drop_index(op.f('ix_tareas_entregas_id'), table_name='tareas_entregas')
    op.drop_table('tareas_entregas')
    op.drop_index(op.f('ix_administradores_id'), table_name='administradores')
    op.drop_index(op.f('ix_administradores_correo'), table_name='administradores')
    op.drop_table('administradores')
    # ### end Alembic commands ###
