"""ampliar material didactico

Revision ID: 9fe0134980ba
Revises: 355a5d84cc6b
Create Date: 2026-09-24 00:12:41.173544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe0134980ba'
down_revision: Union[str, Sequence[str], None] = '355a5d84cc6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materiales_didacticos', sa.Column('descripcion', sa.Text(), nullable=False, server_default=''))
    op.add_column('materiales_didacticos', sa.Column('materia', sa.String(length=150), nullable=False, server_default=''))
    op.add_column('materiales_didacticos', sa.Column('enlace', sa.String(length=500), nullable=False, server_default=''))
    op.add_column('materiales_didacticos', sa.Column('archivo_nombre', sa.String(length=255), nullable=True))
    op.add_column('materiales_didacticos', sa.Column('archivo_base64', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materiales_didacticos', 'archivo_base64')
    op.drop_column('materiales_didacticos', 'archivo_nombre')
    op.drop_column('materiales_didacticos', 'enlace')
    op.drop_column('materiales_didacticos', 'materia')
    op.drop_column('materiales_didacticos', 'descripcion')
    # ### end Alembic commands ###
