"""agregar calificacion a entregas de tareas

Revision ID: afa31b3bcac9
Revises: 9fe0134980ba
Create Date: 2026-09-24 00:38:27.404859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afa31b3bcac9'
down_revision: Union[str, Sequence[str], None] = '9fe0134980ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tareas_entregas', sa.Column('nota', sa.Float(), nullable=True))
    op.add_column('tareas_entregas', sa.Column('retroalimentacion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tareas_entregas', 'retroalimentacion')
    op.drop_column('tareas_entregas', 'nota')
    # ### end Alembic commands ###
