"""conectar convivencia y alertas con seguimiento

Revision ID: f808ee378eef
Revises: 7654e57b857b
Create Date: 2026-09-24 10:54:49.444734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f808ee378eef'
down_revision: Union[str, Sequence[str], None] = '7654e57b857b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alertas_alumnos', sa.Column('docente_nombre', sa.String(length=150), server_default='', nullable=False))
    op.add_column('alertas_alumnos', sa.Column('atendida', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('alertas_alumnos', sa.Column('respuesta_admin', sa.Text(), nullable=True))
    op.add_column('convivencia', sa.Column('titulo', sa.String(length=200), server_default='', nullable=False))
    op.add_column('convivencia', sa.Column('seguimiento_realizado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('convivencia', sa.Column('nota_seguimiento', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convivencia', 'nota_seguimiento')
    op.drop_column('convivencia', 'seguimiento_realizado')
    op.drop_column('convivencia', 'titulo')
    op.drop_column('alertas_alumnos', 'respuesta_admin')
    op.drop_column('alertas_alumnos', 'atendida')
    op.drop_column('alertas_alumnos', 'docente_nombre')
    # ### end Alembic commands ###
