"""esquema inicial

Revision ID: fcb67da00dff
Revises: 
Create Date: 2026-09-21 13:07:05.340100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcb67da00dff'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acudientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acudientes_correo'), 'acudientes', ['correo'], unique=False)
    op.create_index(op.f('ix_acudientes_id'), 'acudientes', ['id'], unique=False)
    op.create_table('comunicados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remitente', sa.String(length=150), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('destinatario_rol', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comunicados_id'), 'comunicados', ['id'], unique=False)
    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_grados_id'), 'grados', ['id'], unique=False)
    op.create_table('profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('especialidad', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profesores_correo'), 'profesores', ['correo'], unique=True)
    op.create_index(op.f('ix_profesores_id'), 'profesores', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=30), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['instructor_id'], ['profesores.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cursos_id'), 'cursos', ['id'], unique=False)
    op.create_table('estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('grado_id', sa.Integer(), nullable=True),
    sa.Column('acudiente_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acudiente_id'], ['acudientes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['grado_id'], ['grados.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudiantes_correo'), 'estudiantes', ['correo'], unique=False)
    op.create_index(op.f('ix_estudiantes_id'), 'estudiantes', ['id'], unique=False)
    op.create_table('alertas_alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.Text(), nullable=False),
    sa.Column('severidad', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_alumnos_id'), 'alertas_alumnos', ['id'], unique=False)
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencias_id'), 'asistencias', ['id'], unique=False)
    op.create_table('calificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('logro', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calificaciones_id'), 'calificaciones', ['id'], unique=False)
    op.create_table('convivencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convivencia_id'), 'convivencia', ['id'], unique=False)
    op.create_table('horarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.String(length=20), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_horarios_id'), 'horarios', ['id'], unique=False)
    op.create_table('materiales_didacticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('archivo_url', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materiales_didacticos_id'), 'materiales_didacticos', ['id'], unique=False)
    op.create_table('matriculas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('fecha_matricula', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['estudiantes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_matricula_estudiante_curso')
    )
    op.create_index(op.f('ix_matriculas_id'), 'matriculas', ['id'], unique=False)
    op.create_table('tareas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tareas_id'), 'tareas', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tareas_id'), table_name='tareas')
    op.drop_table('tareas')
    op.drop_index(op.f('ix_matriculas_id'), table_name='matriculas')
    op.drop_table('matriculas')
    op.drop_index(op.f('ix_materiales_didacticos_id'), table_name='materiales_didacticos')
    op.drop_table('materiales_didacticos')
    op.drop_index(op.f('ix_horarios_id'), table_name='horarios')
    op.drop_table('horarios')
    op.drop_index(op.f('ix_convivencia_id'), table_name='convivencia')
    op.drop_table('convivencia')
    op.drop_index(op.f('ix_calificaciones_id'), table_name='calificaciones')
    op.drop_table('calificaciones')
    op.drop_index(op.f('ix_asistencias_id'), table_name='asistencias')
    op.drop_table('asistencias')
    op.drop_index(op.f('ix_alertas_alumnos_id'), table_name='alertas_alumnos')
    op.drop_table('alertas_alumnos')
    op.drop_index(op.f('ix_estudiantes_id'), table_name='estudiantes')
    op.drop_index(op.f('ix_estudiantes_correo'), table_name='estudiantes')
    op.drop_table('estudiantes')
    op.drop_index(op.f('ix_cursos_id'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_profesores_id'), table_name='profesores')
    op.drop_index(op.f('ix_profesores_correo'), table_name='profesores')
    op.drop_table('profesores')
    op.drop_index(op.f('ix_grados_id'), table_name='grados')
    op.drop_table('grados')
    op.drop_index(op.f('ix_comunicados_id'), table_name='comunicados')
    op.drop_table('comunicados')
    op.drop_index(op.f('ix_acudientes_id'), table_name='acudientes')
    op.drop_index(op.f('ix_acudientes_correo'), table_name='acudientes')
    op.drop_table('acudientes')
    # ### end Alembic commands ###
